/** Activity keys carried over WebSocket and translated by the browser. */
export const ACTIVITY_KEYS = [
	"bubble_maket_doc_new",
	"bubble_maket_doc_list",
	"bubble_maket_doc_delete",
	"bubble_maket_doc_duplicate",
	"bubble_maket_doc_rename",
	"bubble_maket_doc_meta",
	"bubble_maket_doc_export",
	"bubble_maket_doc_import",
	"bubble_maket_page_add",
	"bubble_maket_page_remove",
	"bubble_maket_page_rename",
	"bubble_maket_page_reorder",
	"bubble_maket_canvas",
	"bubble_maket_html_set",
	"bubble_maket_html_patch",
	"bubble_maket_html_check",
	"bubble_maket_workspace_focus",
	"bubble_maket_workspace_state",
	"bubble_maket_workspace_lock",
	"bubble_maket_workspace_fit_view",
	"bubble_maket_workspace_list_messages",
	"bubble_maket_workspace_ack_messages",
	"bubble_maket_charte_list",
	"bubble_maket_charte_view",
	"bubble_maket_charte_set",
	"bubble_maket_charte_delete",
	"bubble_maket_collection_list",
	"bubble_maket_collection_view",
	"bubble_maket_collection_create",
	"bubble_maket_collection_validate_schema",
	"bubble_maket_collection_change_schema",
	"bubble_maket_collection_add_row",
	"bubble_maket_collection_update_row",
	"bubble_maket_collection_delete_row",
	"bubble_maket_collection_delete",
	"bubble_maket_collection_bind",
	"bubble_maket_collection_unbind",
	"bubble_maket_collection_cursor",
	"bubble_maket_image_list",
	"bubble_maket_image_view",
	"bubble_maket_image_meta",
	"bubble_maket_image_import",
	"bubble_maket_image_delete",
	"bubble_maket_preview_open",
	"bubble_maket_preview_snapshot",
	"bubble_maket_mermaid",
	"bubble_maket_pdf",
	"bubble_maket_gmail",
] as const;

export type ActivityKey = (typeof ACTIVITY_KEYS)[number];
